const L=(term,week,strand,title,goal,learn,activityTitle,steps,q,options,a,explain)=>({term,week,strand,title,goal,learn,activity:{title:activityTitle,steps,tip:'No special equipment? Use paper cards, drawings or a teacher-approved simulator and explain the expected result.'},check:{q,options,a,explain}});
window.BOOK={grade:4,lessons:[
// TERM 1
L(1,1,'Internet & E-communications','Inside a smart device','Identify input, processing and output parts in smartphones and tablets.',
['An input sends information into a device, such as a touchscreen, camera or microphone.','Processing is the thinking work done by the device.','An output presents the result, such as sound from a speaker or an image on a screen.'],
'Device detective',['Choose a smartphone or tablet.','Draw it and label two inputs, the processor and two outputs.','Write one input → process → output story, for example taking a photo.'],
'Which part is an input device?',['Speaker','Microphone','Screen'],1,'A microphone captures sound and sends it into the device.'),
L(1,2,'Application Skills','Make text clear and colourful','Format a short document with a heading, paragraph and illustration.',
['Select text before changing its font, size, colour or style.','Bold, italics and underline add emphasis; use them purposefully.','Alignment places text on the left, centre or right of the page.'],
'Create a mini poster',['Type a heading and a four-sentence paragraph about your favourite technology.','Make the heading larger, bold, underlined and centred.','Insert two shapes or pictures, then save the document.'],
'What should you do before changing the colour of words?',['Select the text','Close the document','Press Enter'],0,'Formatting applies to the text you select.'),
L(1,3,'Application Skills','First steps in 2D CAD','Use the CAD interface and line tool to make and save a simple drawing.',
['CAD means Computer-Aided Design.','A line tool creates straight edges between chosen points.','Saving often protects your work and makes it easy to continue later.'],
'Design a robot badge',['Open a CAD or drawing application and start a new drawing.','Use only straight lines to create a simple robot badge.','Save it with a clear filename such as G4_Robot_Badge.'],
'What is CAD mainly used for?',['Designing drawings and models','Sending email','Playing music'],0,'CAD tools help people create accurate designs.'),
L(1,4,'Algorithms & Coding','Words in variables','Create text variables and use ask and join blocks to display user input.',
['A variable is a named container that stores information.','A text variable stores letters, words or sentences.','Ask captures input; join combines pieces of text for a friendly output.'],
'Build a greeting algorithm',['Create text variables called Name and Surname.','Ask the user for both pieces of information and store the answers.','Join the words into a greeting: “Hello, Name Surname!”'],
'Which variable should store “Ayesha”?',['Age','Name','Score'],1,'A name is text, so it belongs in a text variable.'),
L(1,5,'Algorithms & Coding','Numbers in variables','Store a user’s age as a number and display it with text information.',
['A number variable stores values used in counting or calculations.','Variable names should describe their contents, such as age or score.','Text and number variables can both appear in one output message.'],
'Create a learner profile',['Create Name, Surname and Age variables.','Ask for each value and store the answers.','Make a character display a complete profile sentence.'],
'Which is the best variable name for 11?',['colour','age','surname'],1,'The name “age” clearly describes what the number means.'),
L(1,6,'Robotics Skills','Meet the microcontroller','Explain how a microcontroller connects inputs, processing and outputs.',
['A microcontroller is a small programmable computer inside a project.','Inputs send information to it; its program processes that information.','Outputs such as LEDs and buzzers respond to the program.'],
'Map a robot system',['Draw a microcontroller in the centre of a page.','Add two possible inputs on the left and two outputs on the right.','Use arrows to show input → process → output.'],
'What is the microcontroller’s main role?',['Decoration','Processing instructions','Storing paper'],1,'It follows coded instructions and controls connected components.'),
L(1,7,'Robotics Skills','Control light and sound','Use block-based code to switch an LED or buzzer on and off.',
['An LED is a light-emitting output component.','A buzzer is a sound output component.','Code sends HIGH/on or LOW/off instructions to an output pin.'],
'Write an on/off sequence',['Connect or draw an LED/buzzer circuit safely.','Arrange blocks: start → output on → wait → output off.','Predict the result, test it and record whether your prediction was correct.'],
'Which component produces sound?',['LED','Buzzer','Switch'],1,'A buzzer changes electrical energy into sound.'),
L(1,8,'Robotics Skills','Blinking patterns','Use delays to make automatic LED and buzzer patterns.',
['A delay tells the program how long to wait.','A repeated on/off sequence creates a blink or beep pattern.','Changing delay values changes the rhythm.'],
'Code a warning signal',['Plan a four-step light or sound pattern.','Code the pattern with on, wait and off blocks.','Try a shorter delay and describe how the output changes.'],
'What happens when the delay becomes shorter?',['The pattern usually becomes faster','The LED changes into a sensor','The program deletes itself'],0,'Less waiting time produces a faster rhythm.'),
L(1,9,'Assessment','Mini-PAT: define the problem','Write a clear problem statement for a useful electronic solution.',
['A problem statement says who has a need, what the difficulty is and why it matters.','Good designers investigate before choosing a solution.','Requirements describe what a successful solution must do.'],
'Start your design brief',['Choose a real classroom or home problem.','Write: “People need… because…”','List three things your solution must do and one safety rule.'],
'Which statement is most useful?',['Make something cool','Learners need a visible timer so group tasks end on time','Use blue'],1,'It identifies users, a need and the purpose of the solution.'),
L(1,10,'Assessment','Term 1 checkpoint','Review devices, document formatting, variables and microcontroller outputs.',
['Explain input, process and output with your own example.','Compare text and number variables.','Trace an LED on/off program one block at a time.'],
'Teach-back review',['Make four flashcards: device systems, text editing, variables and robotics.','Explain each card aloud without looking at notes.','Return to any card you cannot explain and improve it.'],
'Which sequence is correct?',['Output → input → process','Input → process → output','Process → output → input'],1,'Systems receive input, process it and then produce output.'),

// TERM 2
L(2,1,'Internet & E-communications','Parts of a computer','Identify input, storage, processing and output in laptops and desktop computers.',
['The CPU processes instructions and is sometimes called the “brain” of the computer.','Storage keeps files for later use.','A computer system combines input, processing, storage and output.'],
'Build an IPSO map',['Draw a laptop or desktop computer.','Label keyboard/mouse, CPU, storage and screen/speakers.','Describe what happens when you type and save a sentence.'],
'Which part keeps a file for later?',['Storage','Keyboard','Speaker'],0,'Storage retains data so it can be opened again.'),
L(2,2,'Application Skills','Spreadsheets that calculate','Format a spreadsheet, add and subtract values and make a bar chart.',
['Rows run across and columns run down; their meeting point is a cell.','A formula begins with = and uses cell references.','Charts turn numerical data into a visual comparison.'],
'Create a number lab',['Make columns for Number 1, Number 2, Added and Subtracted.','Enter five pairs of numbers and use formulas for the answers.','Format headings and turn one result column into a bar chart.'],
'Which formula adds cells A2 and B2?',['A2+B2','=A2+B2','=ADD'],1,'Spreadsheet formulas begin with an equals sign.'),
L(2,3,'Application Skills','CAD with three shapes','Combine line, circle and rectangle tools in a saved 2D design.',
['Lines form edges, circles form round features and rectangles form four-sided features.','Complex drawings can be decomposed into simple shapes.','Accurate placement makes a design easier to understand and build.'],
'Design a vehicle icon',['Sketch a vehicle as simple shapes first.','Recreate it in CAD with lines, circles and rectangles.','Save, reopen and check that every part appears correctly.'],
'Which tool is best for a wheel?',['Circle','Line','Text'],0,'A circle tool creates the round outline of a wheel.'),
L(2,4,'Algorithms & Coding','Add and subtract in code','Use number variables with addition and subtraction operators.',
['Operators tell a program to perform a calculation.','Inputs can be stored in variables before they are processed.','The program should label its answer so the user understands the output.'],
'Make a pocket calculator',['Ask for two numbers and store them.','Calculate their sum and difference.','Display both answers with clear labels.'],
'What does the subtraction operator do?',['Combines words','Finds the difference','Repeats code'],1,'Subtraction calculates how much remains or the difference between numbers.'),
L(2,5,'Algorithms & Coding','Multiply and divide in code','Use multiplication and division operators safely and clearly.',
['Multiplication finds equal groups quickly.','Division shares a quantity into equal groups.','A program should avoid division by zero because it has no defined answer.'],
'Build a sharing calculator',['Ask for a total number of items and a number of groups.','Calculate items per group using division.','Also calculate the total for three times as many items.'],
'Which operator shares 24 items among 6 groups?',['Multiply','Divide','Join'],1,'Division splits a total into equal groups.'),
L(2,6,'Robotics Skills','Timing outputs','Control an LED or buzzer with different delay times.',
['Output pins send control signals to components.','Delay values are usually measured in milliseconds or seconds.','Testing one change at a time helps find faults.'],
'Compare three delays',['Create an on/off output sequence.','Test short, medium and long delay values.','Record each value and describe the visible or audible difference.'],
'Which block changes the pause between flashes?',['Wait/delay','Ask','Join'],0,'The wait or delay block controls timing.'),
L(2,7,'Robotics Skills','More than one LED','Control several LEDs to make a colour or traffic-light sequence.',
['Each LED needs a suitable connection and control pin.','Outputs can switch in a planned order.','A sequence is an algorithm with steps in the correct order.'],
'Traffic-light plan',['Draw three LEDs and label them red, amber and green.','Write a safe on/off sequence with delays.','Trace the algorithm with coloured paper circles before coding it.'],
'Why use separate output controls?',['To choose which LED is on','To make the battery larger','To create Wi-Fi'],0,'Separate controls let the program manage each LED.'),
L(2,8,'Robotics Skills','Program an LED pattern','Replicate a given pattern with at least three LEDs.',
['Patterns repeat a recognisable arrangement.','A trace table records the output state after each step.','Testing and correcting are normal parts of coding.'],
'Pattern challenge',['Choose a six-step pattern for three LEDs.','Make a table showing which LEDs are on at every step.','Code or role-play it, find one improvement and retest.'],
'What should you do if step 4 is wrong?',['Delete everything','Debug that step and test again','Ignore it'],1,'Debugging means finding and correcting the fault.'),
L(2,9,'Assessment','Mini-PAT: investigate','Compare possible solutions before selecting one.',
['Investigation gathers facts, user needs and examples.','Criteria help compare ideas fairly.','A labelled sketch communicates how a solution may work.'],
'Solution comparison',['Research or imagine three ways to solve your Term 1 problem.','Score each idea for usefulness, safety and available materials.','Choose one and justify your decision in two sentences.'],
'Why compare several ideas?',['To choose using evidence','To waste time','To avoid solving the problem'],0,'Comparison helps a designer choose a suitable solution.'),
L(2,10,'Assessment','Term 2 exam preparation','Consolidate computer systems, spreadsheets, operators, CAD and LED patterns.',
['Use retrieval practice: answer without notes first.','Show formulas and algorithms step by step.','Check answers against definitions and correct mistakes.'],
'Create a practice paper',['Write two questions for each Term 2 strand.','Answer them without notes and mark them with a different colour.','Rewrite every incorrect answer correctly.'],
'Which is the best way to prepare?',['Only reread','Practise recalling and correct errors','Skip difficult topics'],1,'Active recall plus correction strengthens learning.'),

// TERM 3
L(3,1,'Internet & E-communications','How communication changed','Place indigenous and modern communication methods on a South African timeline.',
['People have long used speech, messengers, drums, signals and written messages.','Digital technology makes communication faster over long distances.','Every method has strengths, limits and a cultural context.'],
'Communication timeline',['Choose six communication methods from different times.','Order and label them on a timeline.','For each, write the message type, speed and intended audience.'],
'What does a timeline show?',['Events in time order','Only modern devices','Spreadsheet formulas'],0,'A timeline shows development and sequence over time.'),
L(3,2,'Application Skills','Your first presentation','Create a clear two-slide presentation with formatted text.',
['A slide should communicate one main idea.','Headings guide the audience; readable text supports the speaker.','Consistent colours and sizes make slides easier to follow.'],
'Two-slide story',['Create a title slide about communication.','Add a second slide with three short facts.','Format text for contrast and practise presenting without reading every word.'],
'What belongs on a good slide?',['A clear main idea','A full page of tiny text','Random colours'],0,'Clear, focused slides support understanding.'),
L(3,3,'Application Skills','Precise 2D CAD','Use line, circle and rectangle tools to copy and improve a design.',
['Start by decomposing the object into basic shapes.','Use alignment and spacing to make parts fit neatly.','Save versions so you can compare improvements.'],
'Create a signal symbol',['Copy a teacher-provided 2D shape or invent a communication symbol.','Use all three drawing tools.','Save version 1, improve one feature and save version 2.'],
'Why decompose a design?',['To see the simple shapes inside it','To add passwords','To change sound'],0,'Breaking a complex design into parts makes it easier to draw.'),
L(3,4,'Algorithms & Coding','Make decisions with if','Use comparison operators and an if-then block to select an outcome.',
['A comparison asks whether a relationship is true or false.','Greater than (>) identifies a larger value; less than (<) identifies a smaller value.','If-then runs its action only when the condition is true.'],
'Number comparer',['Ask for two numbers and store them.','Use if statements to announce the larger and smaller number.','Test equal numbers and decide what your program should say.'],
'Which symbol means greater than?',['>','<','='],0,'The open side faces the larger value: 8 > 3.'),
L(3,5,'Algorithms & Coding','Touching and movement','Combine coordinates, touching and if-then to control a character.',
['The x coordinate moves left/right and y moves down/up.','A touching condition detects contact with an object or edge.','Event triggers start scripts when a key, flag or click occurs.'],
'Edge-return game',['Place a character at a starting coordinate.','Move it to an edge, detect touching and return it to the start.','Add a click counter or keyboard trigger.'],
'Which coordinate changes for left-right movement?',['x','y','time'],0,'The x axis controls horizontal position.'),
L(3,6,'Robotics Skills','Plan a strong structure','Choose components, code and fasteners for a robotics structure.',
['A structure supports and protects parts.','Mechanical fasteners join parts; some are temporary and some permanent.','Planning includes a labelled drawing, component list and code outline.'],
'Project design sheet',['Sketch the structure for your chosen project.','Label microcontroller, LEDs and every fastening point.','List materials and write the intended LED sequence.'],
'What does a fastener do?',['Joins parts','Stores a variable','Searches the internet'],0,'Fasteners connect structural parts.'),
L(3,7,'Robotics Skills','Join parts safely','Select and use a suitable mechanical fastening method.',
['Tape, cable ties, split pins, clips, nuts and bolts suit different needs.','A joint should be strong enough for its purpose.','Safety includes careful tool use and tidy workspaces.'],
'Fastener test',['Make two small card joints using different fasteners.','Test each by gently pulling and bending it.','Record which is stronger and which is easier to undo.'],
'Which fastener is usually reusable?',['Nut and bolt','Glue','Paint'],0,'Nuts and bolts can normally be removed and used again.'),
L(3,8,'Robotics Skills','Build and improve','Construct a basic structure and evaluate its strength and neatness.',
['Making follows the design but allows justified improvements.','Measure twice before cutting or joining.','Evaluation compares the finished product with the requirements.'],
'Structure build',['Build the planned structure from card or available materials.','Check that it stands securely and components have space.','Photograph/draw it and note one change that improved the design.'],
'When should you evaluate?',['During and after making','Never','Only before planning'],0,'Ongoing evaluation catches problems early and judges the result.'),
L(3,9,'Assessment','Mini-PAT: design and make','Combine investigation, design and safe making in a working model.',
['A final design includes dimensions, labels and materials.','A process record shows evidence of planning and making.','A prototype demonstrates the core idea even if it is made from simple materials.'],
'PAT build sprint',['Complete a labelled final drawing.','Build the safest workable prototype you can.','Keep a three-step process record: what you did, what changed and why.'],
'Which is evidence of the process?',['Dated photos and notes','An empty page','Only the product name'],0,'Photos and notes show how the design developed.'),
L(3,10,'Assessment','Term 3 checkpoint','Review communication, presentations, CAD, decisions and structures.',
['Link key words to examples rather than memorising them alone.','Trace code and predict outputs before running it.','Use design vocabulary when explaining structures.'],
'Four-corner review',['Label four pages: communication, applications, coding and robotics.','Add five facts or examples to each from memory.','Use lessons to correct and add missing information.'],
'What does an if block need?',['A condition','A picture only','A file name'],0,'The condition decides whether the action runs.'),

// TERM 4
L(4,1,'Internet & E-communications','Internet benefits and risks','Balance useful e-communication with safe, healthy choices.',
['The internet supports learning, sharing and fast communication.','Risks include too much screen time, harmful messages and false information.','Check the source, author, date and supporting evidence before sharing a claim.'],
'Fake-news detective',['Invent or find a classroom-safe claim.','Check who created it, when, why and what evidence supports it.','Decide: reliable, uncertain or unreliable, and explain why.'],
'What is the safest action with a shocking unverified claim?',['Share immediately','Check reliable sources first','Add an emoji'],1,'Verification prevents false information from spreading.'),
L(4,2,'Application Skills','Four-slide project story','Create a four-slide presentation using headings, images and readable formatting.',
['Slides should follow a beginning, middle and end.','Images must support the message, not distract from it.','High contrast and large text help the audience read.'],
'Present your project',['Plan four slides: problem, design, making and result.','Add at least one useful image and consistent formatting.','Rehearse a two-minute explanation.'],
'Why add an image?',['To support an idea visually','To hide all text','To make the file confusing'],0,'A relevant image can make an explanation clearer.'),
L(4,3,'Application Skills','Record a project video','Record or plan a two-minute video with a title screen.',
['A title screen gives the topic and creator.','A shot list plans what viewers will see in order.','Clear sound, steady framing and permission protect the quality and safety of a video.'],
'Make a video plan',['Write a title and six-shot sequence.','Record or storyboard a two-minute project explanation.','Review it for clear speech, safe content and a logical order.'],
'What belongs at the start of the video?',['A title screen','The final credits only','A spreadsheet formula'],0,'The title screen introduces the video.'),
L(4,4,'Algorithms & Coding','Repeat decisions','Combine repeat blocks, comparisons and multiple if statements.',
['Repeat reduces duplicated code.','A loop can ask for several inputs.','Multiple if statements allow more than one condition to be checked.'],
'Three-round number game',['Repeat three times: ask for two numbers.','Use if statements to identify the larger value and calculate a chosen operation.','Test with a table of expected answers.'],
'Why use repeat?',['To run steps again efficiently','To store a picture','To connect a cable'],0,'Loops repeat instructions without rewriting them.'),
L(4,5,'Algorithms & Coding','Cat-and-mouse game','Use events, x/y movement, sensing, repeat and a score variable in one project.',
['Keyboard events can control a character.','Random movement makes a game less predictable.','A score variable changes when the touching condition becomes true.'],
'Design the chase',['Create cat and mouse characters.','Control the cat with keys and move the mouse repeatedly or randomly.','When touching, increase score and move the mouse away.'],
'What should change when the cat catches the mouse?',['Score variable','Font file','Wi-Fi password'],0,'The score records successful catches.'),
L(4,6,'Robotics Skills','Finish the structure','Strengthen and finish a structure using suitable fasteners.',
['A stable base prevents unwanted movement.','Components need secure positions and space for wires.','Neat finishing makes inspection and repair easier.'],
'Quality check',['Check every joint and gently test stability.','Confirm that no sharp parts or loose wires create danger.','Improve one weak point and record the change.'],
'Which is a sign of good construction?',['Secure joints and tidy parts','Loose wires','An unstable base'],0,'Secure, neat construction is safer and more reliable.'),
L(4,7,'Robotics Skills','Integrate code and construction','Plan and test the LED code, circuit and structure as one system.',
['Integration means combining parts so they work together.','Test code and circuit before fixing components permanently.','Fault finding checks power, connections, component direction and code in order.'],
'System test plan',['List four checks from power to program output.','Test the LED pattern outside the structure first.','Mount components, retest and record the result.'],
'What should you test before permanent mounting?',['The circuit and code','Only the colour','The project name'],0,'Early testing makes faults easier to correct.'),
L(4,8,'Robotics Skills','Build the final system','Complete coding, circuit, process worksheets and the integrated project.',
['Documentation should match the actual circuit and code.','A final build should meet the original requirements.','A demonstration explains input, process and output.'],
'Final assembly',['Complete a circuit diagram and code flow.','Build or model the structure with its microcontroller and outputs.','Demonstrate the system and explain each stage.'],
'What should the circuit worksheet show?',['Connections and components','Only decorations','A history timeline'],0,'A circuit record communicates how electronic parts connect.'),
L(4,9,'Assessment','Final PAT: evaluate and communicate','Evaluate the project honestly and present evidence of learning.',
['Evaluation uses criteria, test evidence and user feedback.','A limitation is something the solution cannot yet do well.','Communication includes the problem, process, outcome and improvement.'],
'PAT reflection',['Test each requirement and mark met, partly met or not met.','Ask one person for useful feedback.','Prepare a short presentation naming one success and one next improvement.'],
'Which is the strongest evaluation?',['“It is nice”','“The LED pattern works, but the base needs more support”','“Finished”'],1,'It uses evidence and identifies an improvement.'),
L(4,10,'Assessment','Final examination review','Retrieve and connect the year’s most important Coding and Robotics ideas.',
['Digital systems follow input, process, storage and output.','Algorithms use variables, operators, conditions, events and loops.','Robotics combines structures, circuits, components, code and evaluation.'],
'Year map',['Draw five branches: e-communication, applications, CAD, coding and robotics.','Add at least eight key ideas to each branch from memory.','Complete one practice question from every term and correct it.'],
'Which statement best describes the year?',['Coding and robotics combines digital, design and problem-solving skills','Only typing matters','Only hardware matters'],0,'The subject integrates knowledge, practical skills and design thinking.')
]};
